- hosts: all
  user: ansible
  become: yes
  gather_facts: no
  tasks:
  - name: Install Apache
    yum: name=httpd state=installed
    run_once: true
    notify: restart httpd
    delegate_to: localhost
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
