---
- hosts: localhost
  become: true
  tasks:
   - name: pip install
     pip:
      name: boto3
      vars:
      ansible_python_interpreter: /usr/bin/python3
   - name: create a simple E2-server
     amazon.aws.ec2_instance:
       name: aadhya
       key_name: XXXXX
       instance_type: t2.micro
       security_group: default
       image_id: ami-17a25d1
       tags:
        Environment: Testing
