---
 - name: Launching aws ec2 instance
   hosts: localhost
   gather_facts: false
   tasks:
   - name: Launching ec2 instance with ec2 module 
     amazon.aws.ec2_instance:
      instance_type: t2.micro
      image: ami-08a0d1e16fc3f61ea
      key_name: ansible_key (pem.key name we need to add)
      region: us-east-1
