

---
- hosts: localhost
  become: true
  tasks:
   - name: pip install
     pip:
      name: boto3
      vars:
      ansible_python_interpreter: /usr/bin/python3
   - name: create a simple E2-server
     amazon.aws.ec2_instance:
       name: aadhya
       count: 2
       key_name: XXXXX
       instance_type: t2.micro
       security_group: default
       image_id: ami-17a25d1
       tags:
        Environment: Testing---

---------------------------------------------------------
      count: 2
      key_name: ansible_key (pem.key name we need to add)
      region: us-east-1
      wait: yes 
      #group: DoWithPython
      #group_id: sg-0afb1127dfd3da9b4
      #group_id: [ 'sg-00fe30710bcfff987','sg-0010cd50d200cfa69']
      group_id:
        - sg-0afb1127dfd3da9b4
        #- sg-0010cd50d200cfa69
      instance_tags:
        Env: test
