---
- hosts: localhost
  become: true
  tasks:
   - name: pip install
     pip:
      name: ["boto3", "botocore"]
     vars:
       ansible_python_interpreter: /usr/bin/python3
   - name: stopped a E2-server
     amazon.aws.ec2_instance:
      instance_ids: i-0b81
      region: us-east-1
      state: stopped
      wait: yes
