- hosts: all
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: first name
      raw: echo "Aadhyamai " > /tmp/LOG1
      tags:
        - firstname
    - name: second name
      raw: echo "Aadhya " > /tmp/LOG2
      tags:
        - secondname
    - name: Thired name
      raw: echo "Aadhya1 " > /tmp/LOG3
      tags:
        - three

